graphprotocol/contracts

- cli/teamAddresses.ts
This makes the CLI build again so it can actually be used. 😉
> cli: Add empty team addresses module (otherwise cli is broken)

- contracts/rewards/RewardsManager.sol
- package-lock.json
- test/rewards/rewards.test.ts
The RewardsManager contract main responsibility is to calculate rewards accrued for allocations based on the total token supply, tokens signalled on subgraphs, accumulated rewards on a subgraph and allocations. Under certain edge condition the calculation could fail and block closing an allocation that would collect rewards.
There is a particular edge case that happens when there are running allocations on a subgraph deployment ID, the total amount of curation signal is removed back to zero and `closeAllocation()` is called by an indexer. If this happens, the indexer won't be able to close that allocation unless it is opting for no rewards by sending POI=0x0. The reason for this is that `getAccRewardsForSubgraph()` is reseting the accumulated rewards for a subgraph when the curation pool …
> Accumulated subgraph rewards reset to zero on edge case

- cli/defaults.ts
- contracts/statechannels/GRTWithdrawHelper.sol
- contracts/statechannels/ICMCWithdraw.sol
- contracts/statechannels/WithdrawHelper.sol
- test/lib/testHelpers.ts
- test/payments/withdrawHelper.test.ts
Introduces a contract called `GRTWithdrawHelper`. The main goal of this contract is to encode custom logic in the process of withdrawing funds from the Vector Channel Multisigs. The contract receives funds from a Channel Multisig, then it forwards them to the Staking contract related to an Allocation.
- The **GRTWithdrawHelper** is deployed with the token address that will be used for transfers, in our case it is the GRT token address. It can't be changed at later stage but this can easily be solved deploying a new contract if needed.
- The contract expects to have available tokens in balance when `execute(WithdrawData calldata wd, uint256 actualAmount)` is called by the Channel. For that to happen the Channel needs to transfer funds to the WithdrawHelper before execute is called. 
- On …
> Withdraw helper contract to support collecting funds from channels

- contracts/disputes/DisputeManager.sol
- contracts/disputes/DisputeManagerStorage.sol
- contracts/disputes/IDisputeManager.sol
- test/disputes/common.ts
- test/disputes/configuration.test.ts
- test/disputes/poi.test.ts
- test/disputes/query.test.ts
- test/lib/deployment.ts
The DisputeManager is the contract where actors in the protocol can create disputes about indexers misbehaving. There are two types of disputes: indexing and query ones. Indexing disputes are created based on one allocation that was closed with a wrong POI (proof of indexing) while query disputes are created presenting an attestation for a wrong query returned. After a dispute is created, the Arbitrator can resolve it and slash a percentage of the indexer's stake.
The PR adds a different slashing percentage for Indexing Disputes and Query Disputes.
The current contract uses the same slashing percentage for indexing and query disputes. However, more flexibility is desirable as one indexing offense can carry much more weight than a single bad query returned. Having a too high slashing …
> Disputes with separate slashing percentages for queries and indexing

- contracts/staking/Staking.sol
Indexers get rewards for indexing subgraphs. These rewards are minted whenever an indexer close an allocation with a non-zero POI. A function called `distributeRewards()` within the Staking contract is used for that purpose. This function calls `RewardsManager.takeRewards()` that updates the snapshots used for rewards calculations and then mint the tokens. In some cases the snapshot calculation is not called.
When an indexer calls `closeAllocation()` with a POI=0x0 the function `distributeRewards()` is not called, as a consequence, `takeRewards()` is not called and in turn the snapshots are not updated before unallocating tokens. This creates a situation where the rewards manager considers there are a different amount of allocated tokens and distort calculations until it is called next …
> Update rewards snapshot when closeAllocation with empty POI

- contracts/governance/Managed.sol
- test/curation/curation.test.ts
- test/lib/fixtures.ts
- test/staking/delegation.test.ts
This is saving between 5% to 15% gas depending on the transaction.
Related to: https://github.com/graphprotocol/contracts/issues/433
> Cache address resolution from the Controller

- contracts/staking/Staking.sol
- test/staking/staking.test.ts
When an indexer decides to unstake their stake completely there might be an opportunity to frontrun that operation through the `stakeTo()` function, making unstake to fail with stake under minimum tokens.
Allow `unstake()` to accept a larger amount than the currently staked tokens. The function will try to unstake the passed amount capped to the available stake.
> Allow unstake passing a larger amount than available

- cli/commands/migrate.ts
- contracts/curation/Curation.sol
- contracts/curation/CurationStorage.sol
- contracts/curation/GraphCurationToken.sol
- contracts/curation/ICuration.sol
- contracts/curation/IGraphCurationToken.sol
- graph.config.yml
- package.json
- test/curation/configuration.test.ts
- test/curation/curation.test.ts
- test/lib/deployment.ts
- test/staking/delegation.test.ts
- yarn.lock
Signal on a subgraph deployment is represented by a subgraph-specific ERC20 token. When signal is minted for a subgraph deployment for the first time, the Curation contract deploys a new ERC20 token. This is costly, about 1.2M gas.
Use a Minimal Proxy to clone the Signal-ERC20 based on an implementation. First mint goes from  1,230,118 gas to 432,840
> Use a minimal proxy for the curation shares ERC20

- contracts/discovery/GNS.sol
- test/gns.test.ts
Closes: https://github.com/OpenZeppelin-Audits/thegraph/issues/3
> Audit: [M01] Semantic overloading of approvals for access control

- contracts/discovery/GNS.sol
- test/gns.test.ts
The SubgraphDeploymentID for the Subgraph was not being updated in the case the Subgraph had zero signal.
> Audit: [X01] Subgraph deployment not updated when no signal

- cli/commands/migrate.ts
- cli/config.ts
- graph.config.yml
- test/curation/curation.test.ts
- Injects `Env` as a variable you can use in the `grapg.config` deployment file to get CLI environment parameters.
- Ensure that deployments from scratch are properly configured for the lastest features in the repo
> Fix deployments and inject cli-env into configuration

- cli/commands/contracts/staking.ts
- contracts/staking/IStaking.sol
- contracts/staking/Staking.sol
- test/disputes/poi.test.ts
- test/disputes/query.test.ts
- test/payments/allocationExchange.test.ts
- test/payments/withdrawHelper.test.ts
- test/rewards/rewards.test.ts
- test/staking/allocation.test.ts
- test/staking/delegation.test.ts
- test/staking/staking.test.ts
Expose a way to batch multiple calls into a single transaction. It provides great flexibility for indexer agents to combine multiple functions in different ways. It also reduce the gas cost by saving the initial gas, and in some cases, accessing a "used" slot by the other bundled transactions.
By using a multicall a user can batch an arbitrary number of operations into a single transaction.
This implementation removes the following functions from the interface to save contract bytecode. They can be now used through a multicall.
- closeAllocationMany()
- closeAndAllocate()
- claimMany()
- allocate() `since allocateFrom() already covers this use case and it's not currently used in production`
> Add multicall to staking contract

- hardhat.config.ts
- scripts/test
- test/lib/fixtures.ts
Since #517, our hardhat local network mines blocks in two ways:
- Automatically when any transaction is sent
- Every 30 seconds
I _suspect_ this is breaking our unit tests for a few reasons:
- CI has started failing quite frequently since that commit
- Several of the failed tests look like timing issues
- I manually timed running tests and noticed errors tend to happen close to 30-second boundaries (though this was a bit of a handwavy measurement).
This PR changes things in two ways:
- For the default local network, disable automining, so transactions will not trigger a mined block, and instead they will _only_ be mined every 30 seconds (@fordN could you confirm if this is the desired behavior?)
- For the unit tests, enable automining and disable the mining interval.
I've run `yarn test` …
> Change the way blocks are mined during testing

- hardhat.config.ts
- scripts/test
- test/lib/fixtures.ts
- test/lib/testHelpers.ts
- test/rewards/rewards.test.ts
(Temporarily targeting the pcv/fix-tests branch as this builds on #554)
Now that blocks are mined predictably in our unit tests (i.e. one block per transaction), any tests that rely on a specific number of blocks passing can break if the number of transactions changes. This was evident when I incorporated the changes from #554 into #552, see: https://github.com/graphprotocol/contracts/runs/5728132209?check_suite_focus=true - adding a transaction in the fixtures bringup caused the test to spill over into the next epoch, changing the results.
So this PR makes a few changes to make tests hopefully more predictable and robust:
- Change the `advanceToNextEpoch` function to always advance to the first block in the next epoch, rather than always advancing a full epoch
- Change several tests that …
> Make block/epoch alignment in tests more predictable

- contracts/gateway/L1GraphTokenGateway.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- test/gateway/l1GraphTokenGateway.test.ts
- test/l2/l2GraphTokenGateway.test.ts
We'll need some trusted contracts to atomically sync state from L1 while sending tokens, so this allows us to do it using the bridge. The whitelist is managed by governance so it won't allow untrusted contract calls.
Example uses (TBD if we'll actually implement these exactly like this, or some other way):
- Sending newly-minted indexer rewards to L2, and at the same time updating the cached total token supply or any other parameters needed for rewards calculation.
- Migrating tokens for GNS curation signal for a subgraph, and creating the subgraph on the L2 GNS.
I'll update GIP-0031 to include this addition.
> Allow callhooks from whitelisted addresses in the Arbitrum GRT bridge

- hardhat.config.ts
- package.json
- tasks/verify/sourcify.ts
- tasks/verify/verify.ts
- yarn.lock
We currently verify our contracts on Etherscan. Sourcify provides a verification service that includes contract metadata verification and a more decentralized approac. See https://blog.soliditylang.org/2020/06/25/sourcify-faq/ for details. 
- Add a `sourcify` hardhat task to verify a contract on https://sourcify.dev/
- Modify solidity settings to generate metadata file on compilation
Usage: 
```bash
npx hardhat sourcify <CONTRACT_ADDRESS> --contract <CONTRACT_FQN> --network mainnet
npx hardhat sourcify 0x147A7758EA71d91D545407927b34DD77A5f7C21A --contract contracts/curation/Curation.sol:Curation --network mainnet
```
Unlike Etherscan, Sourcify requires uploading metadata file generated when contract is compiled. We use the contract's fully qualified name to grab this file.
**Verified …
> Verify contracts with sourcify

- .github/workflows/npmtest.yml
This would allow us to run the tests on PRs that don't target dev because they depend on other PRs, e.g. #571
> ci: run tests on PRs targeting all branches

- addresses.json
Several rinkeby addresses were outdated:
- Curation
- Staking
Also updating RewardsManager to latest implementation address.
> chore: update rinkeby address book

- hardhat.config.ts
- tasks/verify/verify.ts
New command `npx hardhat sourcifyAll --network goerli` will verify all contracts in one go instead of having to individually call and specify contract by contract.
> chore: add hardhat task to verify all contracts with sourcify

- .env.example
- cli/README.md
- tasks/deployment/config.ts
- tasks/gre.ts
- tasks/test-upgrade.ts
- tasks/type-extensions.d.ts
- tasks/verify/verify.ts
- tsconfig.json
This PR refactors the Graph Runtime Environment extension on hardhat. Currently most functionality is not using GRE and is instead using ` loadEnv` which is a similar concept but inherited from the CLI.
In the future we should think about supporting a single environment for our tooling (CLI vs hardhat), the changes proposed to GRE here assume that future is built using hardhat tooling. New features should use GRE and hardhat environment, and we should aim towards slowly integrating the CLI functionality.
GRE now exposes and instanced address book, graph config and contracts:
```js
// Use env vars to determine addressBook (ADDRESS_BOOK) and graphConfig (GRAPH_CONFIG) files 
const { addressBook, contracts, graphConfig } = hre.graph()
const graphTokenEntry = …
```
> feat: refactor graph runtime environment hardhat extension

- package.json
Yarn script `yarn deploy-localhost` was using the default graph config which is `graph.mainnet.yml`. Added the `--graph-config` flag so it uses `graph.localhost.yml`.
> fix: use localhost config for localhost yarn deploy

- contracts/discovery/GNS.sol
- contracts/discovery/IGNS.sol
- test/gns.test.ts
See https://forum.thegraph.com/t/gip-0032-make-gns-signal-transferrable/3338
From GIP32:
> Curators can mint curation shares from a Subgraph Deployment directly on the Curation contract and get fully transferrable ERC20 shares. However, when they curate a Subgraph at the GNS level, the GNS contract is the one keeping all the signal shares under its control. The subgraph curators cannot transfer those shares because the GNS is not exposing any function to do that.
This PR adds a `transferSignal` function to the GNS contract that allows a curator to transfer ownership of their `nSignal` to another address.
> feat: make GNS signal transferable

- config/graph.mainnet.yml
- contracts/rewards/RewardsManager.sol
- contracts/rewards/RewardsManagerStorage.sol
- test/lib/deployment.ts
- test/lib/fixtures.ts
- test/rewards/rewards.test.ts
- test/staking/allocation.test.ts
Current rewards calculation tries to follow a curve `p*r^(t-b) - p`, where `p` is token supply, `r` is issuance rate plus one, `t` is current block and `b` is the block when signal was last updated on any subgraph.
For this to follow the expected curve, however, `p` must correspond to the token supply at block `b`, and not to the time-varying instant supply. This PR fixes the calculation by adding a token supply snapshot, and adds two regression tests that are fixed by this PR and that exemplify the consequences of this bug.
Note that this also changes the `RewardsManager.initialize()` function by removing the call to set issuance rate, since we now need the address of the `GraphToken` contract (to get the supply snapshot) that is not available at initialization time.
> Rewards: fix calculation by using a snapshot of token supply at the time that signal was last updated

- config/graph.goerli.yml
- config/graph.localhost.yml
- config/graph.mainnet.yml
- e2e/deployment/config/rewardsManager.test.ts
PR #569 broke one of the rewards manager e2e config tests as it removed an initialization value from the initializer and instead is setting it with a function call. 
Connected to: #654
> fix: rewards manager e2e config test

- tasks/deployment/accounts.ts
- tasks/deployment/ownership.ts
- tasks/deployment/unpause.ts
- tasks/gre.ts
- tasks/type-extensions.d.ts
Couple of changes to simplify GRE code:
- Use hardhat's `SignerWithAddress` instead of our own `Account`. This is the same account abstraction but widely used by hardhat so there is no point in redefining it.
- `getNamedAccounts` will now always read the named account addresses from the graph config file and initialize a `SignerWithAddress`. This will succeed regardless of wether we hold the private key/mnemonic for the account or not, so we can remove the `VoidSigner` logic to further simplify. If we don't have the private key the signer simply won't be able to sign any transactions.
> Simplify GRE account logic

- cli/commands/migrate.ts
- cli/utils.ts
- config/graph.arbitrum-localhost.yml
- hardhat.config.ts
This PR adds the local nitro networks L1 and L2 to hardhat and fixes a few bugs to allow deploying the protocol to those networks.
- Add local nitro networks (L1 and L2) to hardhat
- Fail gracefully if the network doesn't support `evm_setAutomine` on local networks. Nitro uses geth in dev mode which already has automine behaviour and doesn't support the RPC call.
> feat: add support for local nitro networks

- gre/config.ts
- gre/gre.ts
- gre/test/gre.test.ts
This PR fixes a bug in GRE where it would always connect to the first network in the case where multiple chains are listed in `hardhat.config.ts` with the same chainId. This is most likely to happen with local networks colliding with hardhat's own network (`chainId=1337`).
Now GRE will try to use the main network name (as specified by `--network`) to disambiguate and if that is not enough it will throw an error saying this behavior is not supported.
> fix: ensure GRE handles multiple chains with same chainId gracefully

- contracts/rewards/RewardsManager.sol
- test/rewards/rewards.test.ts
> fix: prevent underflow when subgraphs go under the minimum signal threshold

- contracts/reservoir/L1Reservoir.sol
- test/reservoir/l1Reservoir.test.ts
Simplifies the keeper reward calculation and increases the odds that calling drip immediately after the minDripInterval will be profitable.
> fix: remove minDripInterval from the drip keeper reward calculation [L-01]

- contracts/l2/reservoir/IL2Reservoir.sol
- contracts/l2/reservoir/L2Reservoir.sol
- contracts/l2/reservoir/L2ReservoirStorage.sol
- contracts/reservoir/L1Reservoir.sol
- contracts/reservoir/L1ReservoirStorage.sol
- contracts/reservoir/Reservoir.sol
- contracts/reservoir/ReservoirStorage.sol
- test/l2/l2Reservoir.test.ts
- test/lib/testHelpers.ts
- test/reservoir/l1Reservoir.test.ts
- test/rewards/rewards.test.ts
WIP as I still need to fix the tests.
This complements #571 adding a reward for whoever called drip(), to incentivise calling it and offset the gas costs. The reward is produced through additional token issuance that grows linearly with the number of blocks, after a minimum number of blocks since the last drip have passed.
Note the reward is credited on L1 if the l2RewardsFraction is set to 0. If l2RewardsFraction is nonzero, the reward will be credited in L2, and part of it will be given to the address that initiated the retryable ticket transaction, so that if a lazy or malicious keeper does not redeem the tx in L2, there is incentive for someone else to jump in and redeem it.
> feat: keeper reward for reservoir drip through token issuance

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/npmpublish.yml
- Update test workflow to use node 16 and latest github actions
- Add e2e workflow
- Fix npm publish workflow (hopefully)
Closes: #656, #628
> chore: add e2e tests to github workflows

- .github/workflows/gre.yml
- gre/test/fixture-projects/default-config/hardhat.config.js
- gre/test/fixture-projects/default-config/hardhat.config.ts
- Run `yarn test:gre` when merging to `dev`.
- Fix a bug in GRE tests where test env was picking up project's main `hardhat.config.ts` file instead of a test one due to incorrect file extension (`.js --> .ts`)
> chore: add GRE test to GitHub actions

- gre/config.ts
- gre/helpers/network.ts
- gre/test/config.test.ts
- gre/test/fixture-projects/graph-config-desambiguate/hardhat.config.ts
- gre/test/helpers.ts
GRE uses `chainId` to get details about networks defined in `hardhat.config.ts`. It's possible that there are multiple networks using the same `chainId` so previously we used hardhat's main network name to disambiguate (i.e: `hardhat`, `mainnet`, `localhost`). 
This works as long as the chain id being disambiguated is the main one (specified by the `--network` flag), however it won't work if the secondary network is the one affected. 
For example, for this `hardhat.config.ts`:
```ts
...
networks: {
hardhat: {
chainId: 1337,
},
localhost: {
chainId: 1337,
url: `http://localhost:8545`,
},
localnitrol1: {
chainId: 1337,
url: `http://localhost:8545`,
},
localnitrol2: {
chainId: 412346,
url: 'http://localhost:8547',
},
}
...
```
Running a hardhat command using `--network localnitrol1` will …
> feat(gre): desambiguate chainIds using secondary network name

- .github/workflows/ci.yml
- contracts/gateway/ICallhookReceiver.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- contracts/tests/CallhookReceiverMock.sol
- test/l2/l2GraphTokenGateway.test.ts
- Make the L2 gateway functions non-reentrant for additional safety
- Change the callhooks to only call an `onTokenTransfer` function, to limit the potential impact of a compromised whitelisted L1 sender
> L2 bridge: safer callhook interface

- hardhat.config.ts
Sets sane default values for GRE graph config file path. If necessary they can be overridden by using:
- `--l1-graph-config`, `--l2-graph-config` or `--graph-config` on hardhat tasks
- `hre.graph({ graphConfig: '', l1GraphConfig: '', l2GraphConfig: ''})` when initializing GRE
Refer to GRE documentation for more details: https://github.com/graphprotocol/contracts/tree/dev/gre#configuration
> chore: provide sane defaults for graph config (dev branch)

- hardhat.config.ts
Same as #721 but includes defaults for L2 networks.
> chore: provide sane defaults for graph config (l2-bridge branch)

- .gitignore
- cli/contracts.ts
- gre/gre.ts
- gre/type-extensions.d.ts
Adds an optional wrapper for GRE contract calls, the wrapper will:
- make the contract call and wait for confirmation using `provider.waitForTransaction`
- log transaction details to the console in a "pretty" human readable form
- log transaction details to a file in the projects root directory (`tx-<DATE>.log`)
This will be disabled for now (unless explicitly enabled) because CLI based scripts already have this type of logging using the `sendTransaction` utility. Until we consolidate those (or solve any potential double logging) we shouldn't enable this feature by default.
To try it out simply initialize GRE with `enableTxLogging = true`. Note that running the same script with `enableTXLogging = false` will print nothing to the console.
```ts
const graph = hre.graph({ enableTxLogging: …
```
> feat: add optional expression logging to GRE

- hardhat.config.ts
https://github.com/graphprotocol/contracts/pull/722 was reverted due to the upcoming audit/contest. We should merge this after they are over.
> chore: provide sane defaults for graph config (l2-bridge branch) re-#722

- scripts/test
- Gas report is saved to reports/ folder, but usually we want to see it in the console, so here we add a cat command to print it
- The EVM wasn't being killed properly if the tests failed, so here we add a trap to ensure the cleanup happens
> test: print gas report, and ensure evm is killed

- .gitignore
- e2e/deployment/config/l1/l1GraphTokenGateway.test.ts
- e2e/deployment/config/l2/l2GraphToken.test.ts
- e2e/deployment/config/l2/l2GraphTokenGateway.test.ts
- e2e/deployment/init/l1/bridgeEscrow.test.ts
- scripts/e2e
- tasks/e2e/e2e.ts
This PR adds e2e tests to the bridge contracts (cross checks addresses configured in `L1GraphTokenGateway`, `L2GraphTokenGateway`, `L1GraphToken`, `L2GraphToken` and `BridgeEscrow` match the deployed contract addresses).
> e2e: add bridge e2e tests

- contracts/gateway/GraphTokenGateway.sol
- contracts/gateway/L1GraphTokenGateway.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- e2e/deployment/config/l1/l1GraphTokenGateway.test.ts
- e2e/deployment/config/l2/l2GraphTokenGateway.test.ts
- tasks/deployment/unpause.ts
- test/gateway/l1GraphTokenGateway.test.ts
- test/l2/l2GraphTokenGateway.test.ts
Based on a finding from OZ's audit of #700, but targeting #699 as the change is relevant to that branch too.
> fix: prevent unpausing gateways if they're not configured (OZ M-01 from #700)

- contracts/gateway/GraphTokenGateway.sol
- contracts/l2/token/GraphTokenUpgradeable.sol
Resolves https://github.com/code-423n4/2022-10-thegraph-findings/issues/244
> fix: add storage gaps to GraphTokenGateway and GraphTokenUpgradeable (C4 M-244)

- contracts/gateway/BridgeEscrow.sol
- contracts/gateway/L1GraphTokenGateway.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- contracts/l2/token/L2GraphToken.sol
Resolves https://github.com/code-423n4/2022-10-thegraph-findings/issues/149
> fix: ensure contracts are only initialized once (C4 M-149)

- contracts/gateway/BridgeEscrow.sol
- contracts/gateway/GraphTokenGateway.sol
- contracts/gateway/L1GraphTokenGateway.sol
- contracts/governance/Governed.sol
- contracts/governance/Managed.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- contracts/l2/token/GraphTokenUpgradeable.sol
- contracts/l2/token/L2GraphToken.sol
- contracts/upgrades/GraphProxy.sol
- contracts/upgrades/GraphUpgradeable.sol
- e2e/deployment/config/l1/l1GraphTokenGateway.test.ts
- e2e/deployment/config/l2/l2GraphTokenGateway.test.ts
- test/curation/configuration.test.ts
- test/disputes/configuration.test.ts
- test/gateway/bridgeEscrow.test.ts
- test/gateway/l1GraphTokenGateway.test.ts
- test/gns.test.ts
- test/l2/l2GraphTokenGateway.test.ts
- test/rewards/rewards.test.ts
- test/staking/configuration.test.ts
- test/staking/delegation.test.ts
See https://www.notion.so/edgeandnode/Code4rena-gas-report-notes-3cae3d2fc0304724aec0311b791fa1a7 for details.
> c4: gas optimization fixes

- cli/commands/bridge/to-l2.ts
- contracts/curation/Curation.sol
- contracts/curation/CurationStorage.sol
- contracts/gateway/BridgeEscrow.sol
- contracts/gateway/GraphTokenGateway.sol
- contracts/gateway/ICallhookReceiver.sol
- contracts/gateway/L1GraphTokenGateway.sol
- contracts/governance/Controller.sol
- contracts/governance/Governed.sol
- contracts/governance/Managed.sol
- contracts/governance/Pausable.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- contracts/l2/token/GraphTokenUpgradeable.sol
- contracts/l2/token/L2GraphToken.sol
- contracts/upgrades/GraphProxy.sol
- contracts/upgrades/GraphProxyAdmin.sol
- contracts/upgrades/GraphProxyStorage.sol
- contracts/upgrades/GraphUpgradeable.sol
- e2e/deployment/config/l1/l1GraphTokenGateway.test.ts
- test/gateway/l1GraphTokenGateway.test.ts
- test/l2/l2GraphTokenGateway.test.ts
Relates to several reported issues in https://github.com/code-423n4/2022-10-thegraph-findings/issues
Among others (some of which are duplicates):
https://github.com/code-423n4/2022-10-thegraph-findings/issues/13
https://github.com/code-423n4/2022-10-thegraph-findings/issues/48
https://github.com/code-423n4/2022-10-thegraph-findings/issues/133
https://github.com/code-423n4/2022-10-thegraph-findings/issues/185
https://github.com/code-423n4/2022-10-thegraph-findings/issues/198
https://github.com/code-423n4/2022-10-thegraph-findings/issues/221
https://github.com/code-423n4/2022-10-thegraph-findings/issues/230
https://github.com/code-423n4/2022-10-thegraph-findings/issues/256
https://github.com/code-423n4/2022-10-thegraph-findings/issues/262 …
> C4 QA fixes for #699

- contracts/gateway/L1GraphTokenGateway.sol
- contracts/l2/gateway/L2GraphTokenGateway.sol
- test/gateway/l1GraphTokenGateway.test.ts
- test/l2/l2GraphTokenGateway.test.ts
With the way it worked up to now, `_data.length` would _always_ be nonzero, so we were calling the callhooks always, even when transferring to an EOA! This removes those unnecessary emptyBytes (which were there just to keep the gateway similar to Arbitrum's gateway implementation), and now `_data` on the L2 side will be the callhook data sent from L1, and therefore zero length if there is no callhook to call.
> fix: remove unneeded empty bytes from callhook data

- .github/workflows/e2e.yml
- .gitignore
- TESTING.md
- cli/commands/bridge/to-l1.ts
- cli/commands/bridge/to-l2.ts
- cli/cross-chain.ts
- config/graph.arbitrum-localhost.yml
- e2e/deployment/config/l1/l1GraphTokenGateway.test.ts
- e2e/deployment/config/l2/l2GraphToken.test.ts
- e2e/deployment/config/l2/l2GraphTokenGateway.test.ts
- e2e/deployment/init/l1/bridgeEscrow.test.ts
- e2e/scenarios/fixtures/bridge.ts
- e2e/scenarios/lib/curation.ts
- e2e/scenarios/lib/helpers.ts
- e2e/scenarios/lib/staking.ts
- e2e/scenarios/lib/subgraph.ts
- e2e/scenarios/send-grt-to-l2.test.ts
- e2e/scenarios/send-grt-to-l2.ts
- hardhat.config.ts
- package.json
- scripts/e2e
- tasks/bridge/to-l2.ts
- tasks/deployment/accounts.ts
- tasks/deployment/nitro.ts
- tasks/deployment/ownership.ts
- tasks/deployment/unpause.ts
- tasks/e2e/e2e.ts
- yarn.lock
Previously the e2e testing framework would allow running tests on either an L1 or L2 deployment, with cross-chain messages not being a possibility.
This PR updates the e2e framework so we can now deploy both L1 and L2, configure them fully (including bridge) and have the ability to send L1 <> L2 messages. This requires setting up Arbitrum Nitro local testnodes using the Edge & Node patched fork: https://github.com/edgeandnode/nitro. A new simple scenario that uses the bridge to send GRT from L1 to L2 is also included.
Also updating the GitHub CI action to make use of this, a tl;dr of what the action will now be doing:
- Start an L1 node (geth) and an L2 sequencer connected to it.
- Deploy arbitrum's contracts to L1/L2
- Deploy The Graph protocol to L1/L2
- Configure the protocol (L1, L2, …
> feat(e2e): deploy and configure both layers with the e2e script

- config/graph.goerli.yml
- config/graph.localhost.yml
- config/graph.mainnet.yml
- e2e/deployment/config/l1/rewardsManager.test.ts
Update to match the post merge values.
> Update issuance rate on config files

- cli/arbitrum.ts
- cli/commands/bridge/to-l1.ts
- cli/commands/bridge/to-l2.ts
- tasks/bridge/deposits.ts
- tasks/bridge/withdrawals.ts
- Integrate Arbitrum SDK on `bridge:deposits` and `bridge:withdrawals` tasks to show message status
- Rework how tables are shown a bit.
> feat: integrate bridge tasks with arbitrum sdk

- .github/workflows/verifydeployed.yml
- hardhat.config.ts
- package.json
- tasks/verify/defender.ts
- yarn.lock
Adds a manual github action for verifying deployments. The inputs to the action are the list of contracts to verify and their network. From that, the deployment addresses are picked up from `addresses.json`.
The verify job will use [Defender's API](https://docs.openzeppelin.com/defender/admin#verifying_any_contract) to check that the compiled artifacts at that branch match the ones deployed. An example run can be seen [here](https://github.com/spalladino/graphprotocol-contracts/actions/runs/3594057672).
These results can also be manually checked on Defender after the verification was run.
This workflow requires defining the repository secrets:
- `DEFENDER_API_KEY`
- `DEFENDER_API_SECRET`
- `INFURA_KEY`
> chore: manual action for verifying deployments

- contracts/discovery/IGNS.sol
- contracts/l2/discovery/IL2GNS.sol
- contracts/l2/discovery/L2GNS.sol
- test/l2/l2GNS.test.ts
Prevents a griefing attack in which the subgraph owner leaves all the curators' GRT locked because the subgraph migration is never finished.
Note for gas efficiency we switch from using `migrationData.l1Done == true` to `migrationData.subgraphReceivedOnL2BlockNumber != 0` as an indicator that a subgraph was received from L1.
> fix: allow anyone to deprecate a subgraph if migration is not finished after a week (OZ H-01)

- test/gns.test.ts
- test/l2/l2GNS.test.ts
- test/lib/gnsUtils.ts
> test: additional tests for L2GNS (OZ M-03)

- contracts/discovery/L1GNS.sol
- contracts/discovery/L1GNSStorage.sol
- contracts/l2/curation/IL2Curation.sol
- contracts/l2/curation/L2Curation.sol
- contracts/l2/discovery/IL2GNS.sol
- contracts/l2/discovery/L2GNS.sol
- test/gns.test.ts
- test/l2/l2Curation.test.ts
- test/l2/l2GNS.test.ts
Building on #585 but only sending the owner's signal and allowing curators to send to L2 or withdraw.
Still studying both options, and pending GIP.
> feat: subgraph migration to L2 sending only the owner's tokens (OZ M-01)

- cli/env.ts
Accepts a mnemonic or a private key as argument in the CLI in the `--mnemonic` parameter.
The CLI will figure out if the passed argument match the format of any valid key.
> feat: cli to accept both a mnemonic or private key

- contracts/l2/discovery/IL2GNS.sol
- contracts/l2/discovery/L2GNS.sol
- test/l2/l2GNS.test.ts
The alias works in a similar way to Arbitrum's AddressAliasHelper, but using a uint256 constant added to the subgraphID hash to produce a new L2 subgraphID.
> fix: produce an alias for migrated subgraphIDs

- addresses.json
- package.json
addresses.json will need a new change after updating the implementations, but we need this package before so that Explorer and Studio can start using the new naming as soon as we deploy the contracts.
> chore: use new naming for L2GNS and L2Curation in addresses.json, and bump to 4.0.0

- contracts/staking/Staking.sol
- test/staking/allocation.test.ts
https://github.com/graphprotocol/contracts/pull/838 introduces upgrade testing and a few state transition tests that help validate the code change in this PR.
> fix: Allocations that had a `Claimed` state will now appear with an `Active` state (OZ H-01)

- contracts/l2/staking/L2Staking.sol
- contracts/staking/Staking.sol
This avoid issues when an indexer migrates to L2, then restakes some rewards/fees, so delegators are stuck without being able to quick-withdraw but with an indexer that's under minimum stake.
However, this also affects redeeming migrated stake in L2, because the onTokenTransfer calls `_stake()` (added in #811). This could cause issues if an indexer migrates stake, then withdraws, then migrates some more, so we now won't call `_stake` and just receive the stake without checking the minimum; note this can break the minimum stake invariant, but the indexer will not be able to allocate that stake.
> fix: enforce minimum stake when restaking (OZ M-08)

- contracts/staking/Staking.sol
- test/staking/staking.test.ts
Noted by the OZ team as a bug in #813.
We also change the minimum stake test to use a value closer to the minimum stake, which would catch issues like this a bit better.
> fix: do not double count tokens when checking minimum stake (OZ M-08)

- addresses.json
- package.json
- yarn.lock
Also upgrade hardhat-etherscan to support arbitrum-goerli.
> chore: deploy Staking transfer tools to testnet and bump to 5.0.0

- test/governance/pausing.test.ts
There's currently two tests performing the same actions possibly due to a copy/paste error:
```javascript
it('should fail pause guardian when not governor', async function () {
const tx = controller.connect(me.signer).setPauseGuardian(guardian.address)
await expect(tx).revertedWith('Only Governor can call')
})
it('should fail partial pause if not guardian or governor', async function () {
const tx = controller.connect(me.signer).setPauseGuardian(guardian.address)
await expect(tx).revertedWith('Only Governor can call')
})
```
From test title looks like the second one is meant to be testing that a non governor/guardian shouldn't be able to set partial pause status.
> fix: pausing test for should fail partial pause if not guardian or governor

- addresses.json
- package.json
Looks like we did not update the address book on goerli last time we upgraded the curation contract.
Curation proxy: https://goerli.etherscan.io/address/0xE59B4820dDE28D2c235Bd9A73aA4e8716Cb93E9B
Current impl: https://goerli.etherscan.io/address/0x2b757ad83e4ed51ecae8d4dc9ade8e3fa29f7bdc#code
> chore: update goerli curation implementation details on address book

- contracts/staking/IStakingData.sol
This came up in our Tenderize audits done by Halborn.
> Staking: fix Delegation.tokensLockedUntil code comment

- addresses.json
- arbitrum-addresses.json
- cli/cross-chain.ts
- config/graph.arbitrum-sepolia.yml
- config/graph.sepolia.yml
- gre/helpers/chain.ts
- hardhat.config.ts
- package.json
- tasks/verify/verify.ts
- yarn.lock
Adding sepolia and arbitrum sepolia testnets.
> feat: sepolia testnet

- addresses.json
- package.json
Manually deployed `EthereumDIDRegistry` since there's no Sepolia deployment in https://github.com/uport-project/ethr-did-registry
> feat: added did registry contracts for sepolia

- contracts/discovery/GNS.sol
- test/gns.test.ts
- test/l2/l2GNS.test.ts
Before this fix, if curation or owner tax were zero, GNS would try to mint signal for the new version with zero tokens, which would revert.
> fix(GNS): use the correct token amount when curation or owner tax are zero

- packages/contracts/cli/commands/protocol/configure-bridge.ts
- packages/contracts/e2e/deployment/config/l1/graphToken.test.ts
- packages/contracts/e2e/deployment/config/l1/l1GNS.test.ts
- packages/contracts/e2e/deployment/config/l1/l1Staking.test.ts
- packages/contracts/e2e/deployment/config/l2/l2GNS.test.ts
- packages/contracts/e2e/deployment/config/l2/l2Staking.test.ts
- packages/contracts/tasks/bridge/configure.ts
- packages/sdk/src/deployments/network/actions/bridge-config.ts
Added missing configs on bridge setup, included checks in e2e tests. 
- Set `counterpartGNSAddress` on L1 and L2
- Set `counterpartStakingAddress` on L1 and L2
- Added `L1GNS` and `L1Staking` to `L1GraphTokenGateway.callhookAllowlist`
> fix: add gns and staking counter part addresses when configuring bridge

- .gitignore
- packages/sdk/src/deployments/lib/deploy/contract.ts
- packages/sdk/src/deployments/lib/types/address-book.ts
Currently when using an array in constructor params the result for `address.json` is:
```json
"SubgraphAvailabilityManager": {
"address": "0xcA8B14d9FA8F2a7347782e6B8F334093DCc3789F",
"constructorArgs": [
"0x559081D91F5Ff43dfE51A07C216F8E6893805B35",
"0x9a86322dEa5136C74ee6d1b06F4Ab9A6bB2724E0",
"5",
"300",
"0x840daec5dF962D49cf2EFd789c4E40A7b7e0117D,0x840daec5dF962D49cf2EFd789c4E40A7b7e0117D,0x840daec5dF962D49cf2EFd789c4E40A7b7e0117D,0x840daec5dF962D49cf2EFd789c4E40A7b7e0117D,0x840daec5dF962D49cf2EFd789c4E40A7b7e0117D"
],
"creationCodeHash": "0x70ff001c11d5120782503f0d129f388d8800571f7e9dfbc81bbff048e3a58444",
"runtimeCodeHash": "0x237aca4c61c6d9b391322c0b24e2d26d9d540787507c6d30c474c86866b15dea",
"txHash": "0x66bbfcd338ccdf519ebde1b1656a0dc2716191d49ffdf85986572f65f39cca8f"
}
```
Note …
> chore: add array to constructor argument types

- packages/contracts/tasks/verify/verify.ts
> fix: read config without metadata on verifyAll

- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
- packages/contracts/scripts/prepack
For some reason the publish Action was failing as it was incorrectly interpreting the `*.ts` glob as a filename.
> fix: correctly pass ts file list to tsc in prepack

- packages/contracts/test/unit/gns.test.ts
This Pull Request adds a test case to ensure that the subgraph upgrade does not revert when _curationTaxPercentage is set to 0.
Resolves #891
> test: add _curationTaxPercentage 0 case

- .yarnrc.yml
This fixes problems with dependencies incorrectly declaring deps and messing up hoisting at the root level.
Commit was cherry picked from `horizon` branch.
> chore: ensure yarn doesnt hoist packages past the workspace level

- README.md
- package.json
- packages/eslint-graph-config/.gitignore
- packages/eslint-graph-config/README.md
- packages/eslint-graph-config/eslint.config.js
- packages/eslint-graph-config/index.js
- packages/eslint-graph-config/index.ts
- packages/eslint-graph-config/package.json
- packages/eslint-graph-config/tsconfig.json
- packages/eslint-graph-config/typings/eslint-plugin-no-only-tests.d.ts
- packages/eslint-graph-config/typings/eslint-plugin-no-secrets.d.ts
- packages/solhint-graph-config/README.md
- packages/solhint-graph-config/index.js
- packages/solhint-graph-config/package.json
- packages/solhint-graph-config/prettier.js
- yarn.lock
Inspired by https://github.com/mimic-fi/eslint-mimic-config and https://github.com/mimic-fi/solhint-mimic-config, the idea is to have this standalone configuration packages for linting and formatting. This reduces boilerplate code on each repository and also ensures consistency across them.
A few notes:
- For TypeScript code this is using `eslint` for linting and `stylistic` for formatting. 
- The TypeScript configuration is quite aggressive, for existing projects check out the recommended configuration.
- For Solidity code this is using `solhint` for linting and `prettier` for formatting. 
- Both plugins have a section recommending VSCode extensions and configuration for a proper integration with the IDE.
- For more details see `README.md` for each package.
- Follow up PRs will update …
> feat: add code linting and formatting packages

- packages/eslint-graph-config/README.md
- packages/eslint-graph-config/index.ts
- packages/token-distribution/deploy/1_test.ts
- packages/token-distribution/deploy/2_l1_manager_wallet.ts
- packages/token-distribution/deploy/3_l2_wallet.ts
- packages/token-distribution/deploy/4_l1_transfer_tool.ts
- packages/token-distribution/deploy/5_l2_manager.ts
- packages/token-distribution/deploy/6_l2_transfer_tool.ts
- packages/token-distribution/deploy/lib/utils.ts
- packages/token-distribution/hardhat.config.ts
- packages/token-distribution/ops/create.ts
- packages/token-distribution/ops/delete.ts
- packages/token-distribution/ops/info.ts
- packages/token-distribution/ops/tx-builder.ts
- packages/token-distribution/package.json
- packages/token-distribution/tsconfig.json
Previously the `ignores` key was only being applied to the rules on the custom configuration object, this change forces the ignored paths to apply to all rules.
Also linting some files in `token-distribution` which were incorrectly ignored.
> feat(eslint): properly ignore paths in ignores config

- packages/subgraph-service/contracts/libraries/Allocation.sol
- packages/subgraph-service/contracts/utilities/AllocationManager.sol
- This PR addresses the [following N-10 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-10), applying the recommended fixes.
N-10 Redundant Return Values
Throughout the codebase, multiple instances of functions with unused return values were identified:
The [_closeAllocation](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/subgraph-service/contracts/utilities/AllocationManager.sol#L390) function of the AllocationManager contract
The [presentPOI](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/subgraph-service/contracts/libraries/Allocation.sol#L98), [clearPendingRewards](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa1 …
> fix: remove unused return values. (OZ N-10)

- packages/contracts/contracts/curation/Curation.sol
- packages/contracts/contracts/curation/ICuration.sol
- packages/contracts/contracts/l2/curation/L2Curation.sol
- packages/contracts/contracts/rewards/IRewardsIssuer.sol
- packages/contracts/contracts/staking/Staking.sol
- packages/contracts/contracts/staking/libs/Stakes.sol
- packages/horizon/contracts/interfaces/ITAPCollector.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingExtension.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingMain.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingTypes.sol
- packages/horizon/contracts/payments/GraphPayments.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/contracts/staking/HorizonStakingBase.sol
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/subgraph-service/contracts/DisputeManager.sol
- packages/subgraph-service/contracts/utilities/AllocationManager.sol
- This PR addresses the [following N-07 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-07), applying the recommended fixes.
N-07 Typographical Errors
Throughout the codebase, multiple instances of typographical errors were identified:
[Wether](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStaking.sol#L891) should be "Whether" (also in the [IRewardsIssuer contract](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/contracts/contracts/rewards/IRewardsIssuer.sol#L29C6-L31C54)).
[poriver](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/subgraph-service/contr …
> fix: address typographical errors throughout codebase. (OZ N-07)

- packages/horizon/contracts/libraries/PPMMath.sol
- This PR addresses the [following N-12 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-12), applying the recommended fixes.
##
- Order of parameter use changed from `(MAX_PPM - b, a)` to `(a, MAX_PPM - b)`
> fix: reorder parameter use in mulPPM function call in mulPPMRoundUp function. (OZ N-12)

- packages/horizon/contracts/data-service/extensions/DataServicePausable.sol
- packages/horizon/contracts/data-service/extensions/DataServicePausableUpgradeable.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- This PR addresses the [following N-09 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-09), applying the recommended fixes.
N-09 Missing override Keyword in Functions
Throughout the codebase, multiple instances of functions lacking the override keyword were identified:
The [pause](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/data-service/extensions/DataServicePausable.sol#L33) and [unpause](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/data-service/extensions/DataServicePausable.sol#L40) functions of the DataServicePausable contract
The …
> fix: add override keyword in functions (OZ N-09)

- packages/subgraph-service/contracts/utilities/AllocationManager.sol
- This PR addresses the [following N-06 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-06), applying the recommended fixes.
N-06 Variable Could Be constant
If a variable is only ever assigned a value when it is declared, then it could be declared as constant.
The [EIP712_ALLOCATION_PROOF_TYPEHASH state variable](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/subgraph-service/contracts/utilities/AllocationManager.sol#L31-L32) could be constant.
To better convey the intended use of variables, consider adding the constant keyword to variables that are only set when they are declared.
##
- Updated EIP712_ALLOCATION_PROOF_TYPEHASH to be a constant
> fix: update EIP712_ALLOCATION_PROOF_TYPEHASH from variable to constant. (OZ N-06)

- packages/horizon/contracts/data-service/interfaces/IDataService.sol
- packages/subgraph-service/contracts/libraries/LegacyAllocation.sol
- packages/subgraph-service/contracts/utilities/AllocationManager.sol
- This PR addresses the [following N-02 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-02), applying the recommended fixes.
N-02 Unused Errors
Unused errors can negatively affect code intent and readability.
The [AllocationManagerZeroTokensAllocation](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/subgraph-service/contracts/utilities/AllocationManager.sol#L140), [DataServiceFeatureNotImplemented](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/data-service/interfaces/IDataService.sol#L66), and [LegacyAllocationAlreadyMigrated](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/pa …
> fix: remove unused errors, use LegacyAllocationAlreadyMigrated to prevent migrating a legacy allocation twice (OZ N-02)

- packages/horizon/contracts/payments/GraphPayments.sol
- packages/horizon/contracts/payments/PaymentsEscrow.sol
- packages/horizon/contracts/payments/collectors/TAPCollector.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/subgraph-service/contracts/DisputeManager.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- This PR addresses the [following N-03 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-03), applying the recommended fixes to the contracts outlined. 
N-03 Lack of Security Contact
Providing a specific security contact (such as an email or ENS name) within a smart contract significantly simplifies the process for individuals to communicate if they identify a vulnerability in the code. This practice is quite beneficial as it permits the code owners to dictate the communication channel for vulnerability disclosure, eliminating the risk of miscommunication or failure to report due to a lack of knowledge on how to do so. In addition, if the contract incorporates third-party libraries and a bug surfaces in those, it becomes easier for …
> fix: add security contact to various contract NatSpecs (OZ N-03)

- packages/horizon/contracts/data-service/utilities/ProvisionManager.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- This PR addresses the [following N-11 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-11), applying the recommended fixes.
N-11 Use Constants for Default Values
In the ProvisionManager contract, the [__ProvisionManager_init_unchained function](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/data-service/utilities/ProvisionManager.sol#L151) initializes multiple default values such as type(uint256).min, type(uint256).max, type(uint32).min, type(uint32).max, type(uint64).min, and type(uint64).max directly within the function body.
This approach introduces magic numbers, reducing code readability and maintainability. Moreover, it could potentially introduce errors …
> fix: remove use of magic numbers in __ProvisionManager_init_unchained function (OZ N-11)

- packages/contracts/contracts/disputes/DisputeManager.sol
- packages/horizon/contracts/payments/PaymentsEscrow.sol
- packages/horizon/contracts/staking/HorizonStakingBase.sol
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/subgraph-service/contracts/utilities/AllocationManager.sol
- This PR addresses the [following N-16 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-16), applying the recommended fixes.
##
N-16 Function Visibility Overly Permissive
##
Throughout the codebase, multiple instances of functions with unnecessarily permissive visibility were identified:
The [_verifyAllocationProof](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/subgraph-service/contracts/utilities/AllocationManager.sol#L455-L459) function in AllocationManager.sol with internal visibility could be limited to private.
The [_getDelegatedTokensAvailable](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStak …
> fix: update function visibility (OZ N-16) 

- packages/contracts/contracts/disputes/DisputeManager.sol
- packages/contracts/contracts/governance/Controller.sol
- packages/contracts/contracts/governance/Pausable.sol
- packages/contracts/test/unit/disputes/common.ts
- packages/horizon/contracts/data-service/extensions/DataServiceFees.sol
- packages/horizon/contracts/data-service/interfaces/IDataService.sol
- packages/horizon/contracts/data-service/interfaces/IDataServiceFees.sol
- packages/horizon/contracts/data-service/utilities/ProvisionManager.sol
- packages/horizon/contracts/interfaces/IPaymentsEscrow.sol
- packages/horizon/contracts/payments/PaymentsEscrow.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/test/data-service/extensions/DataServiceFees.t.sol
- packages/horizon/test/data-service/implementations/DataServiceBase.sol
- packages/horizon/test/data-service/implementations/DataServiceBaseUpgradeable.sol
- packages/horizon/test/data-service/implementations/DataServiceImpFees.sol
- packages/horizon/test/data-service/implementations/DataServiceImpPausable.sol
- packages/horizon/test/data-service/implementations/DataServiceImpPausableUpgradeable.sol
- packages/subgraph-service/contracts/DisputeManager.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- packages/subgraph-service/test/SubgraphBaseTest.t.sol
- packages/subgraph-service/test/subgraphService/SubgraphService.t.sol
- packages/subgraph-service/test/subgraphService/provision/accept.t.sol
- packages/subgraph-service/test/utils/Constants.sol
- This PR addresses the [following N-13 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-13), applying some of the recommended fixes.
##
N-13 Naming Suggestions
##
Throughout the codebase, multiple instances where code would benefit from renaming were identified:
- [function releaseStake(uint256 n)](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/data-service/interfaces/IDataServiceFees.sol#L94) could be function releaseStake(uint256 numClaimsToRelease).
- [function _setPartialPaused(bool _toPause)](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/contracts/contracts/governance/Pausable.sol#L36) could be function …
> fix: standardize naming conventions throughout the codebase (OZ N-13)

- packages/horizon/contracts/data-service/extensions/DataServiceRescuable.sol
- packages/horizon/contracts/data-service/interfaces/IDataServiceRescuable.sol
- packages/horizon/contracts/interfaces/IPaymentsEscrow.sol
- packages/horizon/contracts/payments/PaymentsEscrow.sol
- packages/horizon/test/escrow/collector.t.sol
- This PR addresses the [following N-14 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-14), applying the recommended fixes.
##
N-14 Event Emission Suggestions
##
Throughout the codebase, multiple instances of events that could emit additional information were identified:
The [AuthorizedCollector event](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/payments/PaymentsEscrow.sol#L74) could emit the amount for which the collector was authorized.
The [TokensRescued event](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/data-service/extensions/DataServiceRescuable.sol#L72) could emit the token that was …
> fix: emit new events in AuthorizedCollector and TokensRescued. (OZ N-14)

- packages/horizon/contracts/data-service/utilities/ProvisionManager.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingMain.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol
- packages/horizon/test/staking/operator/locked.t.sol
- packages/horizon/test/staking/operator/operator.t.sol
- packages/horizon/test/staking/provision/deprovision.t.sol
- packages/horizon/test/staking/provision/locked.t.sol
- packages/horizon/test/staking/provision/parameters.t.sol
- packages/horizon/test/staking/provision/provision.t.sol
- packages/horizon/test/staking/provision/reprovision.t.sol
- packages/horizon/test/staking/provision/thaw.t.sol
- packages/horizon/test/staking/serviceProvider/serviceProvider.t.sol
- packages/subgraph-service/test/subgraphService/SubgraphService.t.sol
- packages/subgraph-service/test/subgraphService/allocation/start.t.sol
- packages/subgraph-service/test/subgraphService/allocation/stop.t.sol
- packages/subgraph-service/test/subgraphService/collect/query/query.t.sol
- packages/subgraph-service/test/subgraphService/provider/register.t.sol
- packages/subgraph-service/test/subgraphService/provision/accept.t.sol
- This PR addresses the [following N-05 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-05), applying the recommended fixes.
N-05 Inconsistent Parameter and Mapping Order
In the HorizonStaking contract, the [_isAuthorized function](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStaking.sol#L949) has the following parameter order: _operator, _serviceProvider, _verifier. On the other hand, the [_operatorAuth mapping](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStakingStorage.sol#L162) uses this order: _serviceProvider, _verifier, _operator. In addition, the …
> fix: address inconsistent parameter and mapping order (OZ N-05)

- packages/horizon/contracts/interfaces/internal/IHorizonStakingBase.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingExtension.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingMain.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingTypes.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/contracts/staking/HorizonStakingBase.sol
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/horizon/contracts/staking/HorizonStakingStorage.sol
- packages/horizon/test/GraphBase.t.sol
- packages/horizon/test/escrow/collect.t.sol
- packages/horizon/test/payments/GraphPayments.t.sol
- packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol
- packages/horizon/test/staking/HorizonStaking.t.sol
- packages/horizon/test/staking/allocation/close.t.sol
- packages/horizon/test/staking/delegation/addToPool.t.sol
- packages/horizon/test/staking/delegation/delegate.t.sol
- packages/horizon/test/staking/delegation/legacyWithdraw.t.sol
- packages/horizon/test/staking/delegation/redelegate.t.sol
- packages/horizon/test/staking/delegation/undelegate.t.sol
- packages/horizon/test/staking/delegation/withdraw.t.sol
- packages/horizon/test/staking/provision/deprovision.t.sol
- packages/horizon/test/staking/provision/thaw.t.sol
- packages/horizon/test/staking/slash/legacySlash.t.sol
- packages/horizon/test/staking/slash/slash.t.sol
- packages/horizon/test/utils/Constants.sol
- packages/horizon/test/utils/Users.sol
This PR fixes the following issues:
- `TRST-H-2 Core thawing logic of Horizon staking can be broken due to collision in data
structures`
- `TRST-H-3 An attacker could prevent a delegator from ever withdrawing their tokens`
- `TRST-H-4 The last withdrawal from a provision or delegation could permanently revert
due to accounting flaw in slashing`
- `TRST-H-6 During the transition period, legacy allocations cannot be slashed`
- `TRST-H-7 Delegators that began undelegation before the transition would not be able
to withdraw them`
- `TRST-M-3 An attacker could make the minimum delegation amount arbitrarily large
and prevent competing delegations`
- `TRST-M-11 After the transition period, locked amount would still not be available for
use`
- `TRST-M-12 The operator check in closeAllocations() …
> TRST audit fixes for HorizonStaking contract

- README.md
Since #1067 removed the tests... should have done this as part of that PR.
> docs: remove e2e badge from README.md

- README.md
I noticed a typo in the packages table where the path for `solhint-graph-config` was incorrectly pointing to `./packages/eslint-graph-config`.
I’ve updated it to the correct path: `./packages/solhint-graph-config`.
This ensures the documentation accurately reflects the package location.
> fix: Fix incorrect path for solhint-graph-config Update README.md

- packages/contracts/contracts/rewards/IRewardsIssuer.sol
- packages/contracts/contracts/rewards/IRewardsManager.sol
- packages/contracts/contracts/rewards/RewardsManager.sol
- packages/contracts/test/unit/rewards/rewards.test.ts
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- packages/subgraph-service/contracts/interfaces/ISubgraphService.sol
- packages/subgraph-service/contracts/libraries/Allocation.sol
- packages/subgraph-service/contracts/utilities/AllocationManager.sol
- packages/subgraph-service/hardhat.config.ts
- packages/subgraph-service/test/mocks/MockRewardsManager.sol
- packages/subgraph-service/test/shared/SubgraphServiceShared.t.sol
- packages/subgraph-service/test/subgraphService/SubgraphService.t.sol
- packages/subgraph-service/test/subgraphService/allocation/resize.t.sol
- packages/subgraph-service/test/subgraphService/collect/indexing/indexing.t.sol
Changes:
- Added an additional condition to qualify for indexing rewards, the allocation must be at least 1 epoch old.
- Bit of magic to ensure contract is less than 24kB
- Removed `isStaleAllocation()` functionality (to be added back after transition period)
- Removed `isActiveAllocation()` requirement from `IRewardsIssuer`
> feat: dont issue rewards to allos less than one epoch old

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/host-setup.sh
- .devcontainer/project-setup.sh
- .devcontainer/sample-graph.env
- .devcontainer/setup-git-signing.sh
- .gitignore
- .husky/commit-msg
- .husky/pre-commit
- package.json
- yarn.lock
1: Husky pre-commit checks were not working for me.
This fixes them for me, and does a Husky upgrade in the process.
Upgraded Husky produced warnings on pre-commit script, changes there are to solve these and get it working.
2: Dev container configuration.
I use this for local development in a dev container. Might be of some use for others too.
> fix: fix and upgrade Husky pre-commit, and add dev container config

- packages/subgraph-service/contracts/SubgraphService.sol
- packages/subgraph-service/test/subgraphService/provision/accept.t.sol
> fix: prevent indexer lockout in subgraph service (OZ CR-02)

- packages/horizon/contracts/interfaces/internal/IHorizonStakingMain.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/contracts/staking/HorizonStakingBase.sol
- packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol
- packages/horizon/test/staking/provision/thaw.t.sol
> fix: ensure invalid thaw requests are ignored by getThawedTokens (OZ L-01)

- packages/horizon/contracts/interfaces/internal/IHorizonStakingMain.sol
- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol
- packages/horizon/test/staking/provision/provision.t.sol
M-03 was previously L-03, that's why the branch name says `l03`
> fix: prevent provision validity grief attack (OZ M-03)

- packages/horizon/contracts/staking/HorizonStaking.sol
- packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol
- packages/horizon/test/staking/provision/parameters.t.sol
- packages/horizon/test/staking/slash/slash.t.sol
> fix: use solidity division instead of fixed point scaling (OZ L-04)

- packages/horizon/contracts/interfaces/internal/IHorizonStakingBase.sol
- packages/horizon/contracts/interfaces/internal/IHorizonStakingExtension.sol
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol
- packages/horizon/test/staking/slash/legacySlash.t.sol
- packages/horizon/test/staking/slash/slash.t.sol
- packages/subgraph-service/contracts/DisputeManager.sol
- packages/subgraph-service/contracts/interfaces/IDisputeManager.sol
- packages/subgraph-service/test/disputeManager/DisputeManager.t.sol
- packages/subgraph-service/test/disputeManager/disputes/legacy.t.sol
- packages/subgraph-service/test/shared/HorizonStakingShared.t.sol
> fix: prevent legacy slash from breaking provision accounting (OZ H-01)

- packages/contracts/contracts/rewards/IRewardsIssuer.sol
- packages/contracts/contracts/rewards/RewardsManager.sol
- packages/contracts/contracts/staking/IStakingBase.sol
- packages/contracts/contracts/staking/Staking.sol
- packages/contracts/scripts/build
- packages/contracts/test/unit/rewards/rewards.test.ts
- packages/horizon/contracts/staking/HorizonStakingExtension.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- packages/subgraph-service/test/mocks/MockRewardsManager.sol
Tricky bit in `HorizonStakingExtension.sol` is moving the `closedAtEpoch` storage update after the `RewardsManager` internal calls, here: https://github.com/graphprotocol/contracts/pull/1149/files#diff-f0ca33d417ab44fd34813873b594fcfb2dcb852a3bf77c8c3b8ccb88130d9797R378-R380
> fix: ensure getRewards and takeRewards return 0 for closed allos (L-11)

- packages/subgraph-service/contracts/DisputeManager.sol
- packages/subgraph-service/contracts/interfaces/IDisputeManager.sol
- packages/subgraph-service/test/disputeManager/DisputeManager.t.sol
- packages/subgraph-service/test/disputeManager/disputes/indexing/cancel.t.sol
- packages/subgraph-service/test/disputeManager/disputes/query/cancel.t.sol
- packages/subgraph-service/test/disputeManager/disputes/queryConflict/cancel.t.sol
> fix: ensure dispute cancellation is not affected by dispute period change (OZ L-19)

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/project-setup.sh
- .gitignore
- scripts/count-changes
Fixes and updates:
- removing unneeded shared network dependency
- documentation updates
- remove duplicated git signing message
- do not install hardhat (global install not a good idea) 
- install cloc and a script to use it to count Solidity code changes relative to main
- ignore forge-artifacts
scripts/count-changes not about dev container but useful script.
Everything else relates just to dev container configuration.
> Dev container fixes and updates

- packages/address-book/README.md
- packages/address-book/package.json
- packages/address-book/prettier.config.cjs
- packages/address-book/scripts/copy-addresses-for-publish.js
- packages/address-book/scripts/restore-symlinks.js
- packages/address-book/src/horizon/addresses.json
- packages/address-book/src/subgraph-service/addresses.json
- packages/horizon/package.json
- packages/subgraph-service/package.json
- packages/subgraph-service/test/integration/after-transition-period/dispute-manager/indexing-disputes.test.ts
- packages/toolshed/package.json
- packages/toolshed/src/deployments/contract.ts
- packages/toolshed/src/deployments/horizon/actions.ts
- packages/toolshed/src/deployments/horizon/index.ts
- packages/toolshed/src/deployments/subgraph-service/index.ts
- pnpm-lock.yaml
**Description:**
Resolves circular dependency between `horizon`, `subgraph-service` and `toolshed` packages by extracting
shared address book functionality into a new `@graphprotocol/address-book` package.
**Changes:**
- Created `@graphprotocol/address-book` package with symlink-based development workflow
- Updated `toolshed` to use address-book instead of `horizon` and `subgraph-service`
- Added npm publishing scripts to handle symlink-to-file conversion
- Fixed indexing disputes integration tests on the subgraph service
> chore: extract horizon and subgraph-service addresses to a new address-book package

- packages/interfaces/contracts/subgraph-service/ISubgraphService.sol
- packages/interfaces/contracts/toolshed/ISubgraphServiceToolshed.sol
- packages/subgraph-service/contracts/SubgraphService.sol
- packages/subgraph-service/scripts/ops/protocol-activity.ts
- packages/subgraph-service/tasks/test/seed.ts
- packages/subgraph-service/test/unit/shared/SubgraphServiceShared.t.sol
- packages/subgraph-service/test/unit/subgraphService/provider/register.t.sol
**Problem**
The `SubgraphService` contract only allows indexers to register once. This is achieved by reverting calls to the `register()` function if the indexer has `indexer.registeredAt != 0`. The idea behind this limitation is that registering is a "sign up" type of event that should only happen once for any given indexer. 
This in itself does not create problems. However `register()` is the only function that allows setting the indexer's `url` and `geoHash`, meaning that those cannot be changed once the indexer is registered. Since there is no `unregister()` this means that an indexer would be locked forever with the `url` and `geoHash` they initially registered with. 
**Fix**
The proposed fix:
- Eliminates the `indexer.registeredAt !=0` check, allowing indexers to repeatedly call …
> fix: allow indexers from registering multiple times to set registration params

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/project-setup.sh
- .github/actions/setup/action.yml
- .gitignore
- package.json
- packages/contracts/package.json
- packages/contracts/test/hardhat.config.ts
- packages/contracts/test/package.json
- pnpm-lock.yaml
Pnpm
- package.json: Updated packageManager field from pnpm@9.x.x to pnpm@10.17.0
- pnpm-lock.yaml: Regenerated lockfile with pnpm v10 format and updated dependencies
- .github/actions/setup/action.yml: Updated setup action to use pnpm v10
Dev Container
- Updated and simplified dev container configuration for simplicity and better pnpm v10 compatibility
- Dockerfile: Improvements to container setup process
- docker-compose.yml: Updated service configurations
Cleanup & Maintenance
- contracts/test: Removed hardhat-dependency-compiler dependency that was no longer needed
- .gitignore: Added core dump file patterns (core, core.*) to prevent accidental commits
> Upgrade pnpm to v10, and dev container updates
