graphprotocol/contracts

- addresses.json
- cli/defaults.ts
- graph.config.yml
- package-lock.json
- package.json
We have a single package now, and thus, the newest version should always be on master going forwards
> Merge in the v1.1.0 updates into master from testnet

- cli/commands/contracts/curation.ts
Add missing slippage parameter on the transaction call.
> Fix curation slippage in CLI

- .eslintrc
- addresses.json
- cli/address-book.ts
- cli/commands/contracts/governance.ts
- cli/commands/contracts/index.ts
- cli/commands/deploy.ts
- cli/commands/migrate.ts
- cli/commands/proxy/upgrade.ts
- cli/commands/simulations/parseCSV.ts
- cli/network.ts
- contracts/governance/GraphGovernance.sol
- contracts/governance/GraphGovernanceStorage.sol
- contracts/governance/IGraphGovernance.sol
- graph.config.yml
- package.json
- scripts/flatten
- test/governance/gov.test.ts
- test/lib/deployment.ts
- yarn.lock
This PR introduce a contract to govern proposals passed by authorized proposers and approved by a multisig.
The proposals are IPFS hash links that can contain metadata in arbitratry format with the full description of the proposal.
> Add a contract for governance proposals

- test/gns.test.ts
If you like it, feel free to merge it to your branch
> Add more tests for multicall, with event checks

- DEPLOYMENT.md
- README.md
- contracts/rewards/RewardsManager.sol
- contracts/staking/Staking.sol
Complete re-write. It was very out of date.
> Updated README

- scripts/analyze
- Use SARIF json format
- ignore style detectors
- ignore third-party contracts and tests
- skip redundant hardhat compile
> fix slither report

- contracts/discovery/GNS.sol
- test/gns.test.ts
Closes: https://github.com/OpenZeppelin-Audits/thegraph/issues/7
> Audit: [N03] Typographical and grammatical errors

- contracts/discovery/GNS.sol
Closes: https://github.com/OpenZeppelin-Audits/thegraph/issues/5
> Audit: [N01] Lack of input validation

- package.json
- yarn.lock
Confirmed that this fixes #559
> fix: Update hardhat to 2.9.5 to fix console hanging

- cli/commands/migrate.ts
- hardhat.config.ts
Improve deployment speed for local tests with automine while keeping 13s for real condition testing.
> chore: use automine for local deployments

- README.md
- hardhat.config.ts
- Allow to use a mnemonic or single private key 
- Choose whether to use hosted or remote keys when forking
> feat: improve account management

- hardhat.config.ts
- scripts/prepublish
> fix: prepublish script errors

- contracts/l2/gateway/L2GraphTokenGateway.sol
- contracts/l2/reservoir/L2Reservoir.sol
- contracts/reservoir/L1Reservoir.sol
- contracts/reservoir/Reservoir.sol
- contracts/rewards/RewardsManager.sol
s -> outboundCalldata
TOKEN_DECIMALS -> FIXED_POINT_SCALING_FACTOR
> fix: rename some variables for clarity [N-14]

- contracts/reservoir/L1Reservoir.sol
Also prevent the drip from succeeding when the amount to mint is zero.
> fix: don't include keeper reward twice when computing what to send to L2 [H-03] [L-03]

- test/lib/testHelpers.ts
- test/reservoir/l1Reservoir.test.ts
- test/rewards/rewards.test.ts
We also optimize functions to advance blocks in tests, and fix some race conditions that were made evident by this.
> test: add test to ensure no DoS if l2RewardsFraction is zeroed [H-04]

- .github/workflows/e2e.yml
- .github/workflows/gre.yml
Don't run GitHub actions when it's not necessary!
> Run GitHub actions only when it makes sense

- contracts/arbitrum/AddressAliasHelper.sol
Resolves https://github.com/code-423n4/2022-10-thegraph-findings/issues/289
> fix: use unchecked math for address aliasing (C4 M-289 from #699)

- contracts/gateway/L1GraphTokenGateway.sol
Resolves https://github.com/code-423n4/2022-10-thegraph-findings/issues/201
> fix: ensure l2Counterpart is nonzero (C4 M-201)

- package.json
- tasks/bridge/deposits.ts
- tasks/bridge/withdrawals.ts
- yarn.lock
> feat: added tasks to list bridge txs

- config/graph.arbitrum-goerli.yml
- config/graph.arbitrum-one.yml
- config/graph.goerli.yml
- config/graph.mainnet.yml
> chore: rotate account addresses

- addresses.json
- config/graph.arbitrum-goerli.yml
- config/graph.arbitrum-localhost.yml
- config/graph.arbitrum-one.yml
- config/graph.goerli.yml
- config/graph.localhost.yml
- config/graph.mainnet.yml
- e2e/deployment/config/l1/rewardsManager.test.ts
- e2e/deployment/config/l2/rewardsManager.test.ts
- package.json
- Update address book with linear rewards upgraded contracts
- Update graph config files with initial linear rewards parameters (95% / 5% split)
- Bump NPM package version to v3.0.0 (https://www.npmjs.com/package/@graphprotocol/contracts/v/3.0.0)
> chore: update address book with linear rewards upgrade

- contracts/discovery/L1GNS.sol
- test/gns.test.ts
Also warn in the comments about refunds being lost.
> fix(L1GNS): only allow exact msg.value to cover the L2 gas and submission fee (OZ M-01 for #786)

- .env.example
- addresses-staging.json
- hardhat.config.ts
Created `addresses-staging.json` for staging testnet. 
Split `etherscan.apiKey` so we can use different env variables for different networks.
> feat: sepolia staging testnet

- .changeset/config.json
- README.md
- package.json
- yarn.lock
This should simplify the versioning and release process (or at least streamline it).
> chore: add changeset tool

- .github/actions/setup/action.yml
Related to https://github.com/graphprotocol/contracts/issues/901 - it won't _fix_ it, but hopefully the failure rate goes down drastically
> ci: retry yarn build to work around hardhat race condition

- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
- packages/contracts/scripts/prepack
> fix: ensure globbing is enabled in prepack

- packages/token-distribution/contracts/tests/InboxMock.sol
- packages/token-distribution/contracts/tests/L1TokenGatewayMock.sol
- packages/token-distribution/contracts/tests/L2TokenGatewayMock.sol
This pull request contains changes to improve clarity, correctness and structure
> fix: typos in documentation files

- README.md
- packages/hardhat-graph-protocol/CHANGELOG.md
- packages/hardhat-graph-protocol/package.json
- packages/horizon/CHANGELOG.md
- packages/horizon/ignition/configs/migrate.fork1.json5
- packages/horizon/package.json
- packages/subgraph-service/CHANGELOG.md
- packages/subgraph-service/ignition/configs/migrate.fork1.json5
- packages/subgraph-service/package.json
- packages/toolshed/CHANGELOG.md
- packages/toolshed/package.json
- pnpm-lock.yaml
> chore: update address book and bump deps
